//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceptionProcam.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBNCSVisitorEntities : DbContext
    {
        public DBNCSVisitorEntities()
            : base("name=DBNCSVisitorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblVisitor> tblVisitors { get; set; }
        public virtual DbSet<tblIdentityMaster> tblIdentityMasters { get; set; }
    
        public virtual ObjectResult<uspGetVisitorPerDayCount_Result> uspGetVisitorPerDayCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetVisitorPerDayCount_Result>("uspGetVisitorPerDayCount");
        }
    
        public virtual ObjectResult<uspGetVisitorPerDayCount1_Result> uspGetVisitorPerDayCount1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetVisitorPerDayCount1_Result>("uspGetVisitorPerDayCount1");
        }
    }
}
